- name: Make sure glusterd.service is stopped
  systemd:
    state: stopped
    name: glusterd
  become: yes

- name: UnInstall gluster-server
  apt:
    name: "{{ item }}"
    state: absent
    update_cache: yes
  with_items:
    - glusterfs-server
    - xfsprogs
  become: yes


- name: Clean data directory
  file:
    state: absent
    path: /data/glusterfs/myvol1/brick1/*
  become: yes

- name: umount glusterFS disk
  shell: "umount /data/glusterfs/myvol1/brick1"
  become: yes
  ignore_errors: yes

- name: delete diretory GlusterFS data
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /data/glusterfs
    - /var/log/glusterfs/
    - /etc/glusterfs/
    - /etc/systemd/system/glusterd.service
    - /etc/systemd/system/glustereventsd.service
    - /etc/systemd/system/multi-user.target.wants/glusterd.service
    - /etc/systemd/system/generator/*gluster*
    - /mnt/gv/
    - /run/gluster/
    - /run/systemd/generator/data-glusterfs-myvol1-brick1.mount
    - /usr/share/doc/cloud-init/examples/cloud-config-gluster.txt
  become: yes

- name: Recuperar PARTUUID del dispositivo sda1
  shell: blkid -o export /dev/sda1|grep PARTUUID
  register: sda1_partition_uuid
  become: yes

- name:  Limpiar /etc/fstab
  lineinfile:
    state: absent
    path: /etc/fstab
    regexp: "^{{ sda1_partition_uuid.stdout }}"
  become: yes
